#!/usr/bin/env bash
# install mysql for holberton projects
echo 'deb http://repo.mysql.com/apt/ubuntu/ trusty mysql-5.7-dmr' | sudo tee -a /etc/apt/sources.list
sudo apt-get -y update
sudo apt-get install -y mysql-server-5.7

# Install MySQLdb module version 1.3.x
sudo apt-get install -y python3-dev
sudo apt-get install -y libmysqlclient-dev
sudo apt-get install -y zlib1g-dev
sudo pip3 install mysqlclient==1.3.10

# Install SQLAlchemy module version 1.2.x
pip3 install SQLAlchemy==1.2.5
